// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps.js';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = [
      'path',
      'id',
      'parentId',
      'isLayout',
      'isWrapper',
      'layout',
      'clientLoader',
    ];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`,
        );
      }
    });
  });
}

import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': {
      id: 'dumi-context-layout',
      path: '/',
      isLayout: true,
    },
    DocLayout: {
      id: 'DocLayout',
      path: '/',
      parentId: 'dumi-context-layout',
      isLayout: true,
    },
    'docs/components/FormItemsBuilder': {
      path: 'components/form-items-builder',
      id: 'docs/components/FormItemsBuilder',
      parentId: 'DocLayout',
    },
    'docs/components/DetailPresent': {
      path: 'components/detail-present',
      id: 'docs/components/DetailPresent',
      parentId: 'DocLayout',
    },
    'docs/components/FormGenerator': {
      path: 'components/form-generator',
      id: 'docs/components/FormGenerator',
      parentId: 'DocLayout',
    },
    'docs/components/ListTemplate': {
      path: 'components/list-template',
      id: 'docs/components/ListTemplate',
      parentId: 'DocLayout',
    },
    'docs/hooks/useConfigListPage': {
      path: 'hooks/use-config-list-page',
      id: 'docs/hooks/useConfigListPage',
      parentId: 'DocLayout',
    },
    'docs/components/FormModal': {
      path: 'components/form-modal',
      id: 'docs/components/FormModal',
      parentId: 'DocLayout',
    },
    'docs/hooks/useFormModal': {
      path: 'hooks/use-form-modal',
      id: 'docs/hooks/useFormModal',
      parentId: 'DocLayout',
    },
    'docs/about/quickstart': {
      path: 'about/quickstart',
      id: 'docs/about/quickstart',
      parentId: 'DocLayout',
    },
    'docs/hooks/useRequest': {
      path: 'hooks/use-request',
      id: 'docs/hooks/useRequest',
      parentId: 'DocLayout',
    },
    'docs/about/changelog': {
      path: 'about/changelog',
      id: 'docs/about/changelog',
      parentId: 'DocLayout',
    },
    'docs/about/future': {
      path: 'about/future',
      id: 'docs/about/future',
      parentId: 'DocLayout',
    },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'demo-render': {
      id: 'demo-render',
      path: '~demos/:id',
      parentId: 'dumi-context-layout',
      prerender: false,
    },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.14_3wjs623rhauwfddtd2ethvqjym__node_modules__dumi__dist__client__pages__404" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/node_modules/.pnpm/dumi@2.1.14_3wjs623rhauwfddtd2ethvqjym/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/.dumi/tmp/dumi/theme/ContextWrapper.tsx'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.14_3wjs623rhauwfddtd2ethvqjym__node_modules__dumi__theme-default__layouts__DocLayout__index" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/node_modules/.pnpm/dumi@2.1.14_3wjs623rhauwfddtd2ethvqjym/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'docs/components/FormItemsBuilder': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__FormItemsBuilder.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/components/FormItemsBuilder.md'
          ),
      ),
      'docs/components/DetailPresent': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__DetailPresent.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/components/DetailPresent.md'
          ),
      ),
      'docs/components/FormGenerator': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__FormGenerator.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/components/FormGenerator.md'
          ),
      ),
      'docs/components/ListTemplate': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__ListTemplate.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/components/ListTemplate.md'
          ),
      ),
      'docs/hooks/useConfigListPage': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__hooks__useConfigListPage.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/hooks/useConfigListPage.md'
          ),
      ),
      'docs/components/FormModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__FormModal.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/components/FormModal.md'
          ),
      ),
      'docs/hooks/useFormModal': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__hooks__useFormModal.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/hooks/useFormModal.md'
          ),
      ),
      'docs/about/quickstart': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__about__quickstart.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/about/quickstart.md'
          ),
      ),
      'docs/hooks/useRequest': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__hooks__useRequest.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/hooks/useRequest.md'
          ),
      ),
      'docs/about/changelog': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__about__changelog.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/about/changelog.md'
          ),
      ),
      'docs/about/future': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__about__future.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/about/future.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/docs/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.14_3wjs623rhauwfddtd2ethvqjym__node_modules__dumi__dist__client__pages__Demo__index" */ '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/node_modules/.pnpm/dumi@2.1.14_3wjs623rhauwfddtd2ethvqjym/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
