// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/node_modules/.pnpm/dumi@2.1.14_u3samvbzvrksr3cjfq3oe55axi/node_modules/dumi/theme-default/slots/Content/index.js';
