// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jakequc/Desktop/code-space/gitee/art-antd-react/node_modules/.pnpm/dumi@2.1.14_3wjs623rhauwfddtd2ethvqjym/node_modules/dumi/theme-default/slots/Footer/index.js';
